apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
    service: blog
spec:
  ports:
  - name: mysql
    port: {{ .Values.port }}
  clusterIP: None
  selector:
    app: mysql
    service: blog
