apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: kong-tls-redirect@kubernetescrd
spec:
  tls:
  - hosts:
    - blog.jojee.co.kr
    secretName: tls-secret
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: {{ .Values.port }}
