apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.dbName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
data:
  primary.cnf: |
    # Apply this config only on the primary.
    [mysqld]
    log-bin
    character-set-server=utf8mb4
    collation-server=utf8_general_ci
  replica.cnf: |
    # Apply this config only on replicas.
    [mysqld]
    super-read-only
    character-set-server=utf8mb4
    collation-server=utf8_general_ci
