apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.dbName }}-backup
spec:
  schedule: "0 18 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.dbName }}-backup
            image: capjjo/job-db-backup
            imagePullPolicy: Always
            command:
            - /var/run/backup.sh
            env:
            - name: DB_HOST
              value: {{ .Values.dbName }}
            - name: BUCKET
              value: s3://jj-db-backup/blog/
            envFrom:
              - configMapRef:
                  name: {{ .Values.dbName }}-backup
              - secretRef:
                  name: {{ .Values.dbName }}
          restartPolicy: OnFailure
