apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      name: {{ .Release.Name }}
      app: {{ .Values.appName }}
      env: {{ .Values.env }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        name: {{ .Release.Name }}
        app: {{ .Values.appName }}
        env: {{ .Values.env }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap }}
            - secretRef:
                name: {{ .Values.secret }}
        {{- with index .Values.app }}
          command: {{ .cmd }}
          image: {{ .image.repository }}:{{ .image.tag }}
          {{- if .spec }}
          resources:
            limits:
              cpu: {{ .spec.cpu.limits }}
              memory: {{ .spec.memory.limits }}
            requests:
              cpu: {{ .spec.cpu.requests }}
              memory: {{ .spec.memory.requests }}
          {{- end }}
          imagePullPolicy: {{ .image.pullPolicy }}
        {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbePath }}
              port: {{ .Values.port }}
            initialDelaySeconds: 60
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbePath }}
              port: {{ .Values.port }}
            periodSeconds: 5
