apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appName }}
    env: {{ .Values.env }}
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.port}}
