apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: {{ .Values.grafana.host }}
  dnsNames:
    - {{ .Values.grafana.host }}
