env: prod
host: api.blog.jojee.co.kr

app:
  image:
    repository: capjjo/api-blog
    tag: '2af2d72'
    pullPolicy: Always
  spec:
    cpu:
      requests: 500m
      limits: 500m
    memory:
      requests: 1024Mi
      limits: 1024Mi
  cmd: '["java", "-Dfile.encoding=UTF-8", "-Xmx512m", "-jar", "app.jar"]'
