server:
  extraArgs: ["--insecure"]
  config:
    url: "https://argo.jojee.co.kr"
    resource.customizations.ignoreDifferences.ConfigMap: |
      jqPathExpressions:
      - .data
    resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
      jqPathExpressions:
      - '.webhooks[]?.failurePolicy'
    resource.customizations.ignoreDifferences.admissionregistration.k8s.io_ValidatingWebhookConfiguration: |
      jqPathExpressions:
      - '.webhooks[]?.failurePolicy'

  certificate:
    enabled: true
    domain: argo.jojee.co.kr
    issuer:
      name: letsencrypt
      kind: ClusterIssuer
    secretName: tls-secret

  ingress:
    enabled: true
    hosts:
    - argo.jojee.co.kr
    annotations: {
      kubernetes.io/ingress.class: traefik,
      traefik.ingress.kubernetes.io/router.middlewares: kong-tls-redirect@kubernetescrd
    }
    tls:
    - secretName: tls-secret
      hosts:
        - argo.jojee.co.kr
