env: production
host: blog.jojee.co.kr

app:
  image:
    repository: capjjo/web-blog
    tag: '791a699'
    pullPolicy: Always
  spec:
    cpu:
      requests: 200m
      limits: 200m
    memory:
      requests: 256Mi
      limits: 256Mi
  cmd: '["node", "server.js"]'
